import type { SignalTag } from '@/lib/types';

export type DemoSignal = {
  source: string;
  type: string;
  raw_text: string;
  metadata: Record<string, unknown>;
} & SignalTag;

export const demoSignals: DemoSignal[] = [
  {
    source: 'google_review',
    type: 'review',
    raw_text: 'The leather tote is beautiful and feels premium. Delivery took 9 days though, which felt long for the price.',
    sentiment: 'positive',
    topics: ['product quality', 'delivery speed', 'premium pricing'],
    urgency: 'medium',
    metadata: { rating: 4, reviewer: 'demo_customer_1' },
  },
  {
    source: 'facebook_comment',
    type: 'comment',
    raw_text: 'Do you ship outside Dhaka? I wanted to order but could not find a clear delivery estimate.',
    sentiment: 'neutral',
    topics: ['shipping clarity', 'pre-purchase question', 'delivery area'],
    urgency: 'medium',
    metadata: { post: 'summer_launch' },
  },
  {
    source: 'shopify',
    type: 'cart_abandonment',
    raw_text: 'Checkout drop-off increased to 48% this week. Most abandoned carts include the premium tote and happen after shipping costs are displayed.',
    sentiment: 'negative',
    topics: ['abandoned cart', 'shipping cost', 'premium tote'],
    urgency: 'high',
    metadata: { abandonment_rate: 48, product: 'Premium Leather Tote' },
  },
  {
    source: 'support_chat',
    type: 'chat_message',
    raw_text: 'Three customers asked whether the tote fits a 14-inch laptop. The product page only mentions overall dimensions.',
    sentiment: 'neutral',
    topics: ['product details', 'laptop fit', 'support questions'],
    urgency: 'medium',
    metadata: { conversation_count: 3 },
  },
  {
    source: 'instagram_comment',
    type: 'comment',
    raw_text: 'This color is gorgeous. Please restock the forest green version!',
    sentiment: 'positive',
    topics: ['color demand', 'restock request', 'product love'],
    urgency: 'low',
    metadata: { post: 'forest_green_reel' },
  },
  {
    source: 'google_analytics',
    type: 'page_analytics',
    raw_text: 'The tote product page received 1,420 visits in 7 days with a 71% bounce rate. Mobile traffic drove 82% of visits.',
    sentiment: 'neutral',
    topics: ['product page', 'bounce rate', 'mobile traffic'],
    urgency: 'high',
    metadata: { page: '/products/premium-leather-tote', visits: 1420, bounce_rate: 71 },
  },
  {
    source: 'google_review',
    type: 'review',
    raw_text: 'Customer service replied quickly and helped me exchange the size. I would buy again.',
    sentiment: 'positive',
    topics: ['customer service', 'exchange', 'repeat purchase'],
    urgency: 'low',
    metadata: { rating: 5 },
  },
  {
    source: 'facebook_comment',
    type: 'comment',
    raw_text: 'I tried to pay twice and bKash failed both times. Is cash on delivery available?',
    sentiment: 'negative',
    topics: ['payment failure', 'cash on delivery', 'checkout friction'],
    urgency: 'high',
    metadata: { post: 'sale_announcement' },
  },
  {
    source: 'shopify',
    type: 'order_summary',
    raw_text: 'The premium tote generated 34% of revenue this week. Forest green variant sold out 2.4x faster than black.',
    sentiment: 'positive',
    topics: ['best seller', 'color demand', 'revenue'],
    urgency: 'low',
    metadata: { revenue_share: 34, top_variant: 'Forest Green' },
  },
  {
    source: 'support_chat',
    type: 'chat_message',
    raw_text: 'Customers keep asking if returns are free. The returns policy is in the footer but not visible on product pages.',
    sentiment: 'neutral',
    topics: ['returns policy', 'product page clarity', 'support load'],
    urgency: 'medium',
    metadata: { conversation_count: 5 },
  },
  {
    source: 'instagram_comment',
    type: 'comment',
    raw_text: 'Bought this last month and the stitching still looks new after daily use.',
    sentiment: 'positive',
    topics: ['durability', 'quality proof', 'social proof'],
    urgency: 'low',
    metadata: { post: 'customer_story' },
  },
  {
    source: 'google_review',
    type: 'review',
    raw_text: 'Product is great but I received no SMS update before delivery. Please improve communication.',
    sentiment: 'negative',
    topics: ['delivery communication', 'sms updates', 'post-purchase experience'],
    urgency: 'medium',
    metadata: { rating: 3 },
  },
  {
    source: 'facebook_comment',
    type: 'comment',
    raw_text: 'The Eid bundle looks good. Can I choose different colors in the set?',
    sentiment: 'neutral',
    topics: ['bundle customization', 'eid campaign', 'pre-purchase question'],
    urgency: 'low',
    metadata: { post: 'eid_bundle' },
  },
  {
    source: 'shopify',
    type: 'order_summary',
    raw_text: 'Repeat buyers increased 18% month over month. Repeat orders often include wallet add-ons after a tote purchase.',
    sentiment: 'positive',
    topics: ['repeat buyers', 'cross sell', 'wallet add-on'],
    urgency: 'low',
    metadata: { repeat_buyer_growth: 18 },
  },
  {
    source: 'google_analytics',
    type: 'page_analytics',
    raw_text: 'FAQ page traffic grew 39% after the campaign started. Top query from site search: delivery time.',
    sentiment: 'neutral',
    topics: ['faq demand', 'delivery time', 'campaign traffic'],
    urgency: 'medium',
    metadata: { faq_growth: 39, top_search: 'delivery time' },
  },
  {
    source: 'support_chat',
    type: 'chat_message',
    raw_text: 'One angry customer said their order arrived after the birthday date they needed it for.',
    sentiment: 'negative',
    topics: ['late delivery', 'occasion purchase', 'customer frustration'],
    urgency: 'high',
    metadata: { conversation_count: 1 },
  },
  {
    source: 'instagram_comment',
    type: 'comment',
    raw_text: 'Please show more real photos, not just studio shots. I want to see the bag size on a person.',
    sentiment: 'neutral',
    topics: ['real photos', 'size context', 'content request'],
    urgency: 'medium',
    metadata: { post: 'product_photo' },
  },
];
